### ISSUE TITLE
.Artist Command Bug

### ISSUE THREAD

**Issue by ghost** [JBader89/PlugBot#6]
I just encountered a bug on my bot, where the bot crashes out of Plug.DJ, when I type the .artist command into the chatbox while a song is playing.

Error Message:
/var/lib/stickshift/52bdc9f44382ecfb8d000026/app-root/data/704711/node_modules/simple-lastfm/lib/index.js:279
  this._getInfo($.extend(opt, {
                  ^
TypeError: Object function ( w ) {
    if ( !w.document ) {
     throw new Error( "jQuery requires a window with a document" );
    }
    return factory( w );
   } has no method 'extend'
at Lastfm.getArtistInfo (/var/lib/stickshift/52bdc9f44382ecfb8d000026/app-root/data/704711/node_modules/simple-lastfm/lib/index.js:279:19)
    at PlugAPI. (/var/lib/stickshift/52bdc9f44382ecfb8d000026/app-root/data/704711/Plug.DJ
    at PlugAPI.EventEmitter.emit (events.js:95:17)
   at WebSocket. (/var/lib/stickshift/52bdc9f44382ecfb8d000026/app-root/data/704711/Plug.DJ
    at WebSocket.EventEmitter.emit (events.js:98:17)
    at Receiver.self._receiver.ontext (/var/lib/stickshift/52bdc9f44382ecfb8d000026/app-root/data/704711/node_modules/ws/lib/WebSocket.js:697:10)
    at Receiver.opcodes.1.finish (/var/lib/stickshift/52bdc9f44382ecfb8d000026/app-root/data/704711/node_modules/ws/lib/Receiver.js:397:14)
    at Receiver.expectHandler (/var/lib/stickshift/52bdc9f44382ecfb8d000026/app-root/data/704711/node_modules/ws/lib/Receiver.js:384:31)
   at Receiver.add (/var/lib/stickshift/52bdc9f44382ecfb8d000026/app-root/data/704711/node_modules/ws/lib/Receiver.js:93:24)
    at CleartextStream.firstHandler (/var/lib/stickshift/52bdc9f44382ecfb8d000026/app-root/data/704711/node_modules/ws/lib/WebSocket.js:678:22)
    at CleartextStream.EventEmitter.emit (events.js:95:17)
    at CleartextStream.<anonymous> (_stream_readable.js:746:14)
    at CleartextStream.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at _stream_readable.js:401:7
    at process._tickCallback (node.js:415:13)

**Comment by JBader89** [comment]
Could you elaborate about when this is happening? I've never gotten this error myself.

**Comment by ghost** [comment]
While the song is playing and my bot is in the room, I type the .artist command into the chatbox, my bot crashes off of Plug.DJ and Cloud9 switches from Running to Stopped. In the Cloud9 console, it shows the error message.

**Comment by JBader89** [comment]
I don't know what to tell you - this has never happened to me. I tested it and it's still working for me.

**Comment by ghost** [comment]
ok, should I recopy and paste the code for the command into my bot?

**Comment by JBader89** [comment]
I guess so, let me know if that fixes it.

**Comment by ghost** [comment]
I recopied and pasted the code, and it still doesn't work on my bot. All of the other Last FM Commands work with my Lastfm API Account Info for my Bot.

**Comment by JBader89** [comment]
So it's when the song is playing? I know that there is a bug where if you do ".artist" in the chatbox when no song is playing it causes the bot to crash. I chose not to fix this because I assumed there would never be a time when there is no song playing (or at least in the room I hang out in). At this point, that's the only explanation I can think of.

**Comment by ghost** [comment]
ok, what should I do about the bug. Should I not use the .artist Command on my bot until a fix is possible.

**Comment by JBader89** [comment]
I think there is still some miscommunication here; are you saying that the bug occurs when no song is playing? If so, and you find this to be a problem, I can fix it - I just never considered it a big problem. If you're saying that ".artist" isn't working when a song _is_ playing, then I don't know why that is happening for you. For me, ".artist" is working how it should. It may be problem with your code outside the command, I don't know.

**Comment by ghost** [comment]
on my end, The bot crashes when you do the .artist command in the chatbox when the song is playing and when the song is not playing.

**Comment by JBader89** [comment]
I find this worrying, since it's working for me. I can't keep track of all the code changes you make, so I don't know how to help you. I'm closing this issue because it's working for my bot. Sorry I can't be of more assistance.

**Comment by JBader89** [comment]
Only thing I can think of: I noticed that you took away the 'var' declaration before artistChoice in some places. Maybe that's somehow creating a problem? I know this is an unlikely solution, but worth a try.
