### ISSUE TITLE
Plugbotapi

### ISSUE THREAD

**Issue by MomLightVR** [JBader89/PlugBot#9]
Error: Cannot find module 'plugbotapi'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules
\PlugBot-master\bot.js:1:77)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)

but installed ;-)

**Comment by MomLightVR** [comment]
@JBader89

**Comment by JBader89** [comment]
@ChilloutSusan I'm sorry but I haven't worked on this repository in a few years now and don't have time to maintain it. If you would like to make a pull request I would be more than happy to oblige :)
